### ISSUE TITLE
Cannot see room list

### ISSUE THREAD

**Issue by RickyMarts** [SradnickDev/Photon-Example#1]
After I create a room, it doesnt show to other players

**Comment by SradnickDev** [comment]
Do you get any Errors ? are you in the Room ?

**Comment by RickyMarts** [comment]
No errors. I just create a room, but it doesn't appear to the 2nd player. Is it norma?

**Comment by SradnickDev** [comment]
It never happens on my side.  Is the first player in a room after Creating?

**Comment by RickyMarts** [comment]
Yeah

**Comment by SradnickDev** [comment]
Double check when u open a room select 2 or more players, the room isnt visible if full or after 60sec. Or try to debug, check if the 2nd client receive a room list updatw or. Check Photton Settings, I think auto join lobby shouls be enabled.The settings file u find in the Photon project folder
