### ISSUE TITLE
Unity 5.6.5 Help 

### ISSUE THREAD

**Issue by PlayxPE** [SradnickDev/Photon-Example#1]
Estou com problemas para entrar na room , nao da nenhum erro mais quando criar a room

**Comment by SradnickDev** [comment]
Please write in English.

I used Google Translate so I'll try to answer .

I dont used Unity 5.6.5 to create this Project, so its kinda hard to say.But with the next Update I'll implement some more photon callbacks and/debug.logs to debug the code easier.

**Comment by PlayxPE** [comment]
Hello, thank you for replying, my problem is that when I create a room, the create room button does not work, I can not use Unity 2018 because it does not have 32 bits and my notbook does not support 64

**Comment by SradnickDev** [comment]
Ah you have to pick a map before you can create a room, I know there is now rly map picture but one the left

**Comment by PlayxPE** [comment]
sorry to reopen, but I manage to create the room, but back to the login page, you want to download my test project, it only contains your files

**Comment by PlayxPE** [comment]
![img_20180808_171137709](https://user-images.githubusercontent.com/22136548/43861764-301fe03a-9b2e-11e8-832a-73753fd8280a.jpg)

**Comment by SradnickDev** [comment]
That means you solved it ?

**Comment by PlayxPE** [comment]
almost, this everything a beauty my prefab third person etc working, only the login this with a problem that I need to resolve has to do with the small database

**Comment by PlayxPE** [comment]
this menu is for mobile I need a lot to put for mobile

**Comment by SradnickDev** [comment]
It is not made for Mobile so its up to you to made changes you need. The login is atm just a placeholder, later I'll add photon authentication and account registration with a database.

And this is an Example Pack not a out of the box solution, I'll provide example and ideas no fullone project.
